services:
  - type: web
    plan: free
    name: music-player-sasha
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn music_site.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: music_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: music-player-sasha.onrender.com

databases:
  - name: music_db
    plan: free