# Generated by Django 6.0.2 on 2026-04-23 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='artists/', verbose_name='Фото')),
                ('bio', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('type', models.CharField(choices=[('album', 'Альбом'), ('single', 'Сингл'), ('ep', 'EP')], default='album', max_length=10, verbose_name='Тип')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='main.artist', verbose_name='Артист')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('track_number', models.IntegerField(default=1, verbose_name='Номер трека')),
                ('audio_file', models.FileField(upload_to='tracks/', verbose_name='Аудиофайл')),
                ('plays', models.IntegerField(default=0, verbose_name='Прослушивания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='main.album', verbose_name='Альбом')),
                ('artists', models.ManyToManyField(related_name='tracks', to='main.artist', verbose_name='Исполнители')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('tracks', models.ManyToManyField(blank=True, related_name='playlists', to='main.track', verbose_name='Треки')),
            ],
        ),
    ]
