# Generated by Django 6.0.2 on 2026-06-28 19:46

import cloudinary.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='tracks/', verbose_name='Аудиофайл'),
        ),
    ]
